// =============================================================
// TIPOS — Plataforma de Aprendizagem Adaptativa
// =============================================================

// ============================
// Autenticação & Usuário
// ============================

export type VarkStyle = 'visual' | 'auditory' | 'reading' | 'kinesthetic';

export interface SportsProfile {
  practiced: string[];    // esportes que pratica
  liked: string[];        // esportes que gosta
  followed: string[];     // modalidades que acompanha
  level: string;          // iniciante | intermediário | avançado | atleta
}

export interface StudyPreference {
  summaryLength: 'short' | 'detailed';
  prefersExamples: boolean;
  prefersRealCases: boolean;
  learningMode: string;
}

export interface LearningProfile {
  id: string;
  userId: string;
  // Dimensões VARK
  visualScore: number;
  auditoryScore: number;
  readingScore: number;
  kinestheticScore: number;
  primaryStyle: VarkStyle;
  secondaryStyle: VarkStyle | null;
  // Perfil esportivo e profissional
  sportsProfile: SportsProfile | null;
  careerGoal: string | null;
  studyPreference: StudyPreference | null;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  picture: string | null;
  varkCompleted: boolean;   // true = onboarding completo
  learningProfile: LearningProfile | null;
}

// ============================
// Onboarding
// ============================

export type VarkDimension = 'V' | 'A' | 'R' | 'K';

export interface VarkQuestion {
  id: string;
  text: string;
  options: { value: VarkDimension; label: string }[];
}

export interface VarkAnswer {
  questionId: string;
  answer: VarkDimension;
}

export interface VarkResult {
  primaryStyle: VarkStyle;
  secondaryStyle: VarkStyle | null;
  scores: {
    visual: number;
    auditory: number;
    reading: number;
    kinesthetic: number;
  };
  description: string;
  studyTips: string[];
  learningProfile: LearningProfile;
}

export interface OnboardingPayload {
  answers: VarkAnswer[];
  sportsProfile: SportsProfile;
  careerGoal: string;
  studyPreference: StudyPreference;
}

// ============================
// Classroom
// ============================

export type PreparationStatus = 'PENDING' | 'PROCESSING' | 'READY' | 'ERROR';

export interface Course {
  id: string;
  googleId: string;
  userId: string;
  name: string;
  section: string | null;
  description: string | null;
  courseState: string | null;
  enrollmentCode: string | null;
  alternateLink: string | null;
  preparationStatus: PreparationStatus;
  preparedAt: string | null;
  preparationError: string | null;
  createdAt: string;
  updatedAt: string;
  _count?: {
    materials: number;
    assignments: number;
  };
  materials?: Material[];
  assignments?: Assignment[];
}

export interface MaterialAttachment {
  type: string;
  title: string;
  url?: string;
  driveFileId?: string;
  mimeType?: string;
  thumbnailUrl?: string;
}

export interface Material {
  id: string;
  googleId: string;
  courseId: string;
  title: string;
  description: string | null;
  type: 'material' | 'announcement';
  state: string | null;
  alternateLink: string | null;
  attachments: MaterialAttachment[] | null;
  extractedText: string | null;
  publishedAt: string | null;
  createdAt: string;
  updatedAt: string;
  course?: { name: string; id: string };
}

export interface Assignment {
  id: string;
  googleId: string;
  courseId: string;
  title: string;
  description: string | null;
  dueDate: string | null;
  maxPoints: number | null;
  state: string | null;
  workType: string | null;
  alternateLink: string | null;
  createdAt: string;
  updatedAt: string;
  course?: { name: string; id: string };
}

// ============================
// Conteúdo de Estudo (gerado automaticamente)
// ============================

export type ContentType = 'summary' | 'flashcards' | 'quiz' | 'study_guide';

export interface GeneratedContent {
  id: string;
  userId: string;
  materialId: string | null;
  courseId: string | null;
  type: ContentType;
  content: string;
  varkStyle: VarkStyle;
  sourceTitle: string | null;
  autoGenerated: boolean;
  createdAt: string;
  material?: { title: string; id: string } | null;
}

export interface CourseGeneratedContentResponse {
  courseId: string;
  courseName: string;
  preparationStatus: PreparationStatus;
  preparedAt: string | null;
  preparationError: string | null;
  materials: Array<{
    materialId: string;
    materialTitle: string;
    availableTypes: ContentType[];
    isProcessed: boolean;
  }>;
  processedCount: number;
  totalCount: number;
}

/** Status de conteúdo disponível por material */
export interface MaterialContentStatus {
  materialId: string;
  materialTitle: string;
  availableTypes: ContentType[];
  isProcessed: boolean;
}

/** Resposta da API de conteúdo por material */
export interface MaterialContentResponse {
  material: { id: string; title: string; course: { name: string } };
  content: Record<ContentType, GeneratedContent | null>;
  hasContent: boolean;
}

// Estruturas internas do JSON gerado
export interface Flashcard {
  front: string;
  back: string;
  sport_example?: string;
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correct: number;
  explanation: string;
}

export interface StudyGuide {
  title: string;
  goal: string;
  totalDays: number;
  days: Array<{
    day: number;
    theme: string;
    duration: string;
    activities: Array<{
      title: string;
      description: string;
      sport_connection?: string;
    }>;
  }>;
  tips: string[];
}

// ============================
// Dashboard
// ============================

export interface DashboardData {
  courses: Course[];
  upcomingAssignments: Assignment[];
  recentMaterials: Material[];
  learningProfile: LearningProfile | null;
  stats: {
    totalCourses: number;
    totalMaterials: number;
    totalAssignments: number;
  };
}

// ============================
// Utilitários
// ============================

export interface ApiResponse<T> {
  success: boolean;
  data: T;
  message?: string;
}
