/**
 * Serviço de Preparação de Conteúdo Adaptado
 *
 * Gera resumos e flashcards personalizados para os materiais de uma disciplina.
 * Só é chamado quando o aluno abre uma disciplina — nunca durante o sync.
 *
 * Regra de cache: antes de chamar a OpenAI, verifica se já existe
 * GeneratedContent para (userId, materialId, type). Se existir, pula.
 */
import { PrismaClient, Prisma } from '@prisma/client';
import * as aiService from './ai.service';
import { logger } from '../utils/logger';

const prisma = new PrismaClient();

const TYPES_TO_GENERATE: aiService.ContentType[] = ['summary', 'flashcards'];

/**
 * Inicia a preparação de uma disciplina em background (fire-and-forget).
 * Retorna imediatamente após setar o status para PROCESSING.
 */
export async function prepareCourse(userId: string, courseId: string): Promise<void> {
  await prisma.course.update({
    where: { id: courseId },
    data: { preparationStatus: 'PROCESSING', preparationError: null },
  });

  setImmediate(() => {
    runPreparation(userId, courseId).catch((err) =>
      logger.error('Erro fatal no pipeline de preparação', { err, userId, courseId })
    );
  });
}

/**
 * Pipeline completo de preparação — executa em background.
 */
async function runPreparation(userId: string, courseId: string): Promise<void> {
  logger.info('Iniciando preparação de conteúdo', { userId, courseId });

  try {
    const user = await prisma.user.findUnique({
      where: { id: userId },
      include: { learningProfile: true },
    });

    if (!user?.learningProfile) {
      await prisma.course.update({
        where: { id: courseId },
        data: {
          preparationStatus: 'ERROR',
          preparationError: 'Complete o onboarding antes de preparar materiais.',
        },
      });
      return;
    }

    const course = await prisma.course.findFirst({
      where: { id: courseId, userId },
      include: {
        materials: {
          where: { type: 'material' },
          orderBy: { createdAt: 'desc' },
        },
      },
    });

    if (!course) return;

    if (course.materials.length === 0) {
      await prisma.course.update({
        where: { id: courseId },
        data: { preparationStatus: 'READY', preparedAt: new Date() },
      });
      return;
    }

    const profile = buildStudentProfile(user.learningProfile);

    for (const material of course.materials) {
      const attachments = (material.attachments as Array<{ title?: string }> | null) || [];
      const attachmentTitles = attachments.map((a) => a.title).filter(Boolean) as string[];

      const contentText = aiService.prepareMaterialText(
        material.title,
        material.description,
        material.extractedText,
        attachmentTitles
      );

      if (!contentText.trim()) continue;

      for (const type of TYPES_TO_GENERATE) {
        // Regra de cache — não regenera o que já existe
        const existing = await prisma.generatedContent.findFirst({
          where: { userId, materialId: material.id, type },
        });
        if (existing) continue;

        try {
          const result = await aiService.generateContent({
            type,
            profile,
            courseName: course.name,
            materialTitle: material.title,
            content: contentText,
          });

          await prisma.generatedContent.create({
            data: {
              userId,
              materialId: material.id,
              courseId,
              type,
              content: result.content,
              varkStyle: profile.varkStyle,
              sourceTitle: material.title,
              autoGenerated: true,
            },
          });

          logger.debug(`${type} gerado`, { materialId: material.id, userId });
        } catch (err) {
          logger.warn(`Falha ao gerar ${type} para material ${material.id}`, { err });
        }
      }
    }

    await prisma.course.update({
      where: { id: courseId },
      data: { preparationStatus: 'READY', preparedAt: new Date() },
    });

    logger.info('Preparação concluída', { userId, courseId });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Erro desconhecido';
    logger.error('Erro na preparação', { err, userId, courseId });

    await prisma.course.update({
      where: { id: courseId },
      data: { preparationStatus: 'ERROR', preparationError: message },
    });
  }
}

// ============================================================
// Helpers
// ============================================================

type LearningProfileRecord = NonNullable<
  Prisma.UserGetPayload<{ include: { learningProfile: true } }>['learningProfile']
>;

function buildStudentProfile(profile: NonNullable<LearningProfileRecord>): aiService.StudentProfile {
  const sportsData = profile.sportsProfile as { practiced?: string[]; liked?: string[] } | null;
  const studyPref = profile.studyPreference as {
    summaryLength?: 'short' | 'detailed';
    prefersExamples?: boolean;
    prefersRealCases?: boolean;
  } | null;

  return {
    varkStyle: profile.primaryStyle as aiService.VarkStyle,
    secondaryStyle: profile.secondaryStyle,
    sports: [
      ...(sportsData?.practiced || []),
      ...(sportsData?.liked || []),
    ].slice(0, 5),
    careerGoal: profile.careerGoal,
    prefersExamples: studyPref?.prefersExamples ?? true,
    prefersRealCases: studyPref?.prefersRealCases ?? true,
    summaryLength: studyPref?.summaryLength ?? 'detailed',
  };
}
